source 'https://rubygems.org'

gem 'rake'

gem 'thin'

gem 'sinatra'
gem 'sinatra-contrib'

gem 'sinatra-websocket'
gem 'sinatra-activerecord'

gem 'redis'

group :development do
  gem 'sqlite3'
end
group :production do
  gem 'mysql2'
end
